### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/Virtual-Agents-Prototype#24]
There should be pages in the documentation that answer the following questions:

- What do I need to do to create an agent from scratch with the given components? Which components are absolutely necessary to drive the agent?
- How can I exchange the avatar of the agent?
- How can I add new tasks for the agent to perform?
- How can I make the agent perform a task?
- How can I add new animations to the agent and integrate them into the existing infrastructure?

**Comment by danielbekhter** [comment]
Created four Wiki pages to answer these questions.
